import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Tilt from 'react-vanilla-tilt';
import Link from 'next/link'

// images
import blm from '../img/BLM.png';
import sah from '../img/SAH.png';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
      </Head>

      <Tilt className={styles.tilt}>
      <main className={styles.main}>
        <h1 className={styles.title}>
          &quot;If you&apos;re silent about your pain, they&apos;ll kill you and say you enjoyed it.&quot; <br/> -Zora Neale Hurtson
        </h1>

        <p className={styles.description}>
          A reflection on <a href="https://www.youtube.com/watch?v=myreT4oTcIY&feature=youtu.be&ab_channel=CargoFilm%26Releasing" className={styles.movie}>Marshawn Lynch: A History</a>
        </p>
          <nav className={styles.navbar}>
            <div>
              <Image
                alt="Black Lives Matter"
                height={50}
                width={90}
                src={blm}/>
            </div>
            <div>
              <strong><Link href="/intro">Pt. I</Link></strong>
            </div>
            <div>
              <Image
                alt="Stop Asian Hate"
                height={90}
                width={90}
                src={sah}/>
            </div>
          </nav>
        </main>
        </Tilt>
    </div>
  )
}

export default Home
